### ISSUE TITLE
Hackathon input Kids and Nuclear Gorillas

### ISSUE THREAD

**Issue by HorstCodeGorilla** [codeGorillaNL/EducationDesign#24]
Game setup like an RPG

Game must be entertaining

It should primarily fun

There must be different themes

There should be interaction between players

It should be objective

Players should be able teach each other 

You should be able to find other players based on their skills

There should be different skill levels

Avatars

Their should be a trade system

Peer to Peer

There should be visual selection options

The game should be adaptive

Solving issues should make for progress

There should be minigames within the game

You should be able to travel between worlds

There should be an open world

Unity

Outdoors options

Alliances can be formed

Collectible items to build stuff

Energy efficient transportation

Choose your own skills

Transportation between worlds

The game should have action elements

Skill boosts with exploring new skills

You should always have to have something to do

No agression

The game should be humorous and cartoony

Players should be able to communicate via text / speak

Players should learn by playing the game

There should be sports available in the game (agility etc.)

Taunting other players should be possible (victory dances, etc.)

Funny K.O.’s

**Comment by rschoemaker12** [comment]
Sneeuwitje and the bits

Modular for teachers.
Learning goal editable and free to build in module.
Reward learning across different learning goals.
Reward learning in depth into learning goals.
Monitoring learning progress by teacher possible by access of choices and choices.
Steering of self learning process by awarding bonus for specific choices by teachers.
Possibility to work in groups for group reward.
Game of theme-park building in3D and (VR possible)
More themes means more leaning goals
A more visual pleasing theme is higher level of learning goal

Gamepark building in 3D VR
