### ISSUE TITLE
Plans

### ISSUE THREAD

**Issue by Bijbrengen** [codeGorillaNL/EducationDesign#7]
A individual design can be exported as a solid learning plan suitable for teachers to determine it's potential. The design of a park can be exported as a schoolplan suitable for an education inspector. Both plans have the quality so that the receiver can not refuse it.

**Comment by HorstCodeGorilla** [comment]
Would using these guidelines create a learning plan of the intended quality? https://www.dlsweb.rmit.edu.au/toolbox/leadership/toolbox/ls/ls_c06.html

**Comment by Bijbrengen** [comment]
Thank you

2017-04-26 8:37 GMT+02:00 Ramon <notifications@github.com>:
